apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-portal-ingress
  namespace: api-portal
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  tls:
  - hosts:
    #! - api-portal.akslab2a.tap.fynesy.com
    - secretName: api-portal-tls-cert
  rules:
  - host: api-portal.akslab2a.tap.fynesy.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: api-portal-server
            port:
              number: 8080