apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tdemo-gateway-cert
  namespace: default
spec:
  dnsNames:
  - tdemo.akslab2a.tap.fynesy.com
  secretName: tdemo-gateway-cert-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer