apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: spring-petclinic-gateway-route
  namespace: default
spec:
  service:
    name: spring-petclinic
  routes:
  - predicates:
      - Path=/petclinic/**
      - order=1000
    filters:
      - StripPrefix=1
      - PrefixPath=/
  - predicates:
      - Path=/petclinic/webjars/**
      - order=1
    filters:
      - StripPrefix=0
      - PrefixPath=/
  - predicates:
      - Path=/petclinic/resources/**
      - order=2
    filters:
      - StripPrefix=0
      - PrefixPath=/