apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: spring-petclinic-gateway-route
  namespace: default
spec:
  service:
    name: spring-petclinic
  routes:
  - predicates:
      - Path=/petclinic/**
    filters:
      - StripPrefix=1
      - PrefixPath=/
    order: 1000
  - predicates:
      - Path=/petclinic/webjars/**
    filters:
      - StripPrefix=0
      - PrefixPath=/
    order: 1
  - predicates:
      - Path=/petclinic/resources/**
    filters:
      - StripPrefix=0
      - PrefixPath=/
    order: 2