apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: spring-petclinic-gateway-route
  namespace: default
spec:
  service:
    name: spring-petclinic
  routes:
  - predicates:
      - Path=/petclinic/**
    filters:
      - StripPrefix=1
      - PrefixPath=/
      - RewritePath=/webjars(?<segment>/?.*),/petclinic/webjars/$\{segment}
      - RewritePath=/resources(?<segmentb>/?.*),/petclinic/resources/$\{segmentb}
    order: 1000
  #- predicates:
  #    - Path=/webjars/**
  #  filters:
  #    - StripPrefix=0
  #    - PrefixPath=/
  #  order: 1
  #- predicates:
  #    - Path=/resources/**
  #  filters:
  #    - StripPrefix=0
  #    - PrefixPath=/
  #  order: 2